### ISSUE TITLE
Unable to set default currency

### ISSUE THREAD

**Issue by Stephan-MC** [givehug/money-lib#22]
Please i am unable to use the money.config() function to set the default currency. 

error: Property 'config' does not exist on type '(money?: Money | ChainedMoney | undefined) => ChainedMoney'.

**Comment by givehug** [comment]
> Please i am unable to use the money.config() function to set the default currency.
> 
> error: Property 'config' does not exist on type '(money?: Money | ChainedMoney | undefined) => ChainedMoney'.

Hey, I just release 1.6.3 with the fix. Thanks for noticing. Let me know.
